name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: .Net SDK Project file Version
      uses: jasondavis303/net-sdk-proj-file-version@v1.0.1
      with:
        PROJ_FILE: BOTW_SaveConv.csproj 
    - name: Install dependencies
      run: dotnet restore BotWSaveManager.sln
    - name: Build
      run: dotnet build BotWSaveManager.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
